### ISSUE TITLE
Cannot play some channels

### ISSUE THREAD

**Issue by qwerttvv** [rozhuk-im/msd_lite#2]
hi,

[raw.zip](https://github.com/rozhuk-im/msd_lite/files/10434780/raw.zip)

Here is the original raw file from the channel

Use [msd_lite](https://github.com/rozhuk-im/msd_lite)  [e254782](https://github.com/rozhuk-im/msd_lite/commit/e254782c0f2199f5351cc7dae1d0be3ebaa5a7f0) to play, there is  only sound without video, but udpxy is good, perfect display video and sound.

**Comment by MageDelfador** [comment]
Same problem.
请问问题解决了吗？

**Comment by MageDelfador** [comment]
可能是这个问题
https://github.com/rozhuk-im/msd_lite/pull/5
