### ISSUE TITLE
Stop playing problem

### ISSUE THREAD

**Issue by CHDman** [rozhuk-im/msd_lite#4]
I use MSD and UDPXY to watch IPTV for 5 minutes and it will stop playing，then I use UDPXY to add a parameter to solve this problem, but MSD does not have this parameter, can you add it?

![12345566](https://user-images.githubusercontent.com/20582736/211162780-ec86c8e2-705b-4aea-b3c3-97219ff4e950.jpg)
（option mcsub_renew '55'）

MSD is very efficient and easy to use, love it, thank you.

**Comment by rozhuk-im** [comment]
No.
This is workaround that do IGMP LEAVE + IGMP JOIN (mld for ipv6).
In well configured environment OS periodically receive IGMP (mld) message that requires to confirm subscription to multicast groups.
If OS does not confirm subscription then nearest L2 switch with IGMP snooping threat this as IGMP lLEAVE and stop transmit multicast group to client port.

Check your firewall, it must allow IGMP traffic to 224/4, also it must allow IP OPTIONS.

This is FreeBSD PF rules that I use:
```
pass out quick inet proto udp to 224.0.0.0/4 no state allow-opts
pass out quick inet proto igmp to 224.0.0.0/4 no state allow-opts
pass out quick inet6 proto icmp6 no state allow-opts # mld (igmp6) also here
pass out quick inet6 proto udp to ff00::/8 no state allow-opts # Allow send multicast, DHCPv6 ff02::1:2 port 547

pass in quick inet proto udp to 224.0.0.0/4 no state allow-opts
pass in quick inet proto igmp to 224.0.0.0/4 no state allow-opts
pass in quick inet6 proto udp to ff00::/8 no state # Allow receive multicast, DHCPv6 ff02::1:2 port 547
pass in quick inet6 proto icmp6 no state allow-opts # mld (igmp6) also here
```

**Comment by wanjiban** [comment]
same qustion .
install to side router , no firewall issue .
and stop play at about every 4:20 .

**Comment by rozhuk-im** [comment]
Check msd_lite log for errors.
I suppose problem with IGMP in your network environment.

Some firewalls (FreeBSD PF) does not pass IP packets with options by default, so even if you have ```pass all``` rule, IGMP will not work.

Also make sure that router/host does not have routes to any 224/4 subnets in routing tables.

Use tcpdump to debug network issues, for example: ```tcpdump -n -e -vvvvvvv -i __NETWORK_INTERFACE_NAME__ ip and igmp```.

**Comment by CHDman** [comment]
> No. This is workaround that do IGMP LEAVE + IGMP JOIN (mld for ipv6). In well configured environment OS periodically receive IGMP (mld) message that requires to confirm subscription to multicast groups. If OS does not confirm subscription then nearest L2 switch with IGMP snooping threat this as IGMP lLEAVE and stop transmit multicast group to client port.
> 
> Check your firewall, it must allow IGMP traffic to 224/4, also it must allow IP OPTIONS.
> 
> This is FreeBSD PF rules that I use:
> 
> ```
> pass out quick inet proto udp to 224.0.0.0/4 no state allow-opts
> pass out quick inet proto igmp to 224.0.0.0/4 no state allow-opts
> pass out quick inet6 proto icmp6 no state allow-opts # mld (igmp6) also here
> pass out quick inet6 proto udp to ff00::/8 no state allow-opts # Allow send multicast, DHCPv6 ff02::1:2 port 547
> 
> pass in quick inet proto udp to 224.0.0.0/4 no state allow-opts
> pass in quick inet proto igmp to 224.0.0.0/4 no state allow-opts
> pass in quick inet6 proto udp to ff00::/8 no state # Allow receive multicast, DHCPv6 ff02::1:2 port 547
> pass in quick inet6 proto icmp6 no state allow-opts # mld (igmp6) also here
> ```

Thanks for your reply, I used the option multicast subscription renew  of udpxy to solve this problem, does msd_lite have option multicast subscription renew? If not, can you add this option? Thanks

**Comment by rozhuk-im** [comment]
No, msd_lite does not have renew/rejoin option.

Yes, I can add this work around.
Can you build and test it?

**Comment by CHDman** [comment]
> No, msd_lite does not have renew/rejoin option.
> 
> Yes, I can add this work around. Can you build and test it?

I use Openwrt OS. The Chinese New Year is coming soon, and I am a little busy, so I may not have time to build it. If you can build it, I will test it. Thanks a lot！^_^

**Comment by CHDman** [comment]
> > No, msd_lite does not have renew/rejoin option.
> > Yes, I can add this work around. Can you build and test it?
> 
> I use Openwrt OS. The Chinese New Year is coming soon, and I am a little busy, so I may not have time to build it. If you can build it, I will test it. Thanks a lot！^_^

BTW：Openwrt X86

**Comment by rwzsycwan** [comment]
> No, msd_lite does not have renew/rejoin option.
> 
> Yes, I can add this work around. Can you build and test it?

I need this, my iptv can only watch 2 minutes and 10 seconds, after this time Destroyed will appear in the log. I will build and test it。

**Comment by rwzsycwan** [comment]
> > No, msd_lite does not have renew/rejoin option.
> > Yes, I can add this work around. Can you build and test it?
> 
> I need this, my iptv can only watch 2 minutes and 10 seconds, after this time Destroyed will appear in the log. I will build and test it。

In UDPXY, if mcsub_renew '55' is not set, the channel can only play for 2 minutes and 10 seconds.

**Comment by tangyl2000** [comment]
> No, msd_lite does not have renew/rejoin option.
> 
> Yes, I can add this work around. Can you build and test it?

I met the same problem, my iptv streaming stopped every 4:20 minutes. But I set udpxy “option mcsub_renew” to 240,  iptv streaning never stopped. 
If you can add this option code, I have enough time to build and test is.

**Comment by rwzsycwan** [comment]
This is translated with google:
     In my city, the telecom operator's iptv multicast network has heartbeat verification, and if there is no report information for a period of time, the multicast data will be disconnected.
     I use igmp proxy on the router. When I start to join the multicast, IGMP Proxy will send the Report from the Host Interface to the IGMP Querier. The IGMP Proxy sends the Query message to the member hosts on behalf of the IGMP Querier, and the IGMP Proxy will not feed back the Report message to the IGMP Querier.
     After more than 2 minutes (the time may be different in different cities), because the IGMP Querier does not receive new report information, it will disconnect the multicast data. Since the live stream is disconnected, msd_lite will send a leave message to igmp proxy, and IGMP Proxy will notify the upstream IGMP Querier through the group leaving mechanism.
     That's about it.

**Comment by MageDelfador** [comment]
This is the firewall problem of home routers. Occurs when UDP forwarding is allowed but igmp forwarding is not allowed.
The problem is like this:
```
【Home router】                     【ISP】
                 igmp join->>
                <<-Multicast udp data
	            (After 1 minute)
	        <<-igmp query (Blocked by firewall, so no response)
	            (After 1 minute)
	        <stop sending udp data>
```
It is really not a good idea to use the renew function of udpxy. It will cause packet loss.https://github.com/pcherenkov/udpxy/issues/28

**Comment by rwzsycwan** [comment]
> 



> 这是家用路由器的防火墙问题。当允许 UDP 输入但不允许 igmp 输入时发生。 问题是这样的：
> 
> ```
> 【Home router】                     【ISP】
>                  igmp join->>
>                 <<-Multicast udp data
> 	            (After 1 minute)
> 	        <<-igmp query (Blocked by firewall, so no response)
> 	            (After 1 minute)
> 	        <stop sending udp data>
> ```
> 
> 使用udpxy的renew功能确实不是什么好主意。会造成丢包。[pcherenkov/udpxy#28](https://github.com/pcherenkov/udpxy/issues/28)



> This is the firewall problem of home routers. Occurs when UDP input is allowed but igmp input is not allowed. The problem is like this:
> 
> ```
> 【Home router】                     【ISP】
>                  igmp join->>
>                 <<-Multicast udp data
> 	            (After 1 minute)
> 	        <<-igmp query (Blocked by firewall, so no response)
> 	            (After 1 minute)
> 	        <stop sending udp data>
> ```
> 
> It is really not a good idea to use the renew function of udpxy. It will cause packet loss.[pcherenkov/udpxy#28](https://github.com/pcherenkov/udpxy/issues/28)

My routers are MikroTik Routers. I have enabled igmp and udp accept in the firewall. I used Packet sniffer to capture packets on the iptv port. I didn’t get any igmp query from ISP, only Membership Report / Join group ip for any sources or Membership Report / Leave group ip.

**Comment by MageDelfador** [comment]
@rwzsycwan 看防火墙是不是允许igmp的输入(目标是本设备，不是转发)
不要启用igmp代理

**Comment by rwzsycwan** [comment]
> 



> @rwzsycwan 看防火墙是不是允许igmp的输入(目标是本设备，不是转发) 不要启用igmp代理

问题已经解决了，我的路由器的防火墙配置是正确的，换了原来电信的光猫，就好了，收到了来自ISP到224.0.0.1的Query。猫棒还是有问题，收不到来自ISP的Query，有空抓包看看猫棒为什么扔了这些数据。

**Comment by rwzsycwan** [comment]
> 

我的iptv需要pppoe拨号，不开启igmp代理内网看不了。

**Comment by MageDelfador** [comment]
> @MageDelfador 我的iptv需要pppoe拨号，不开启igmp代理内网看不了。

正常不需要igmp代理，msd_lite接口配置成pppoe-iptv就可以了。

**Comment by MageDelfador** [comment]
@CHDman @tangyl2000 @wanjiban 
Is the problem solved?

**Comment by rozhuk-im** [comment]
https://github.com/rozhuk-im/msd_lite/tree/rejoin - branch to test rejoin feature.

```<rejoinTime>0</rejoinTime>``` was added to config file.
Also ```rejoin_time=60``` can be used as URL argument.
0 - off, non zero - interval in second to rejoin multicast group.


PS: I prefer to archive this project, is was free demo for https://github.com/rozhuk-im/msd, that now is open source and free.

**Comment by rwzsycwan** [comment]
> > @MageDelfador 我的iptv需要pppoe拨号，不开启igmp代理内网看不了。
> 
> 正常不需要igmp代理，msd_lite接口配置成pppoe-iptv就可以了。

我路由器是MikroTik的rb450gx4，运行不了msd_lite，我是在内网里旁路由上运行的

**Comment by CHDman** [comment]
> https://github.com/rozhuk-im/msd_lite/tree/rejoin - branch to test rejoin feature.
> 
> `<rejoinTime>0</rejoinTime>` was added to config file. Also `rejoin_time=60` can be used as URL argument. 0 - off, non zero - interval in second to rejoin multicast group.
> 
> PS: I prefer to archive this project, it was free demo for https://github.com/rozhuk-im/msd, that now is open source and free.

Thanks a lot, I will test it when I have time.

> https://github.com/rozhuk-im/msd_lite/tree/rejoin - branch to test rejoin feature.
> 
> `<rejoinTime>0</rejoinTime>` was added to config file. Also `rejoin_time=60` can be used as URL argument. 0 - off, non zero - interval in second to rejoin multicast group.
> 
> PS: I prefer to archive this project, it was free demo for https://github.com/rozhuk-im/msd, that now is open source and free.

Thanks a lot, I will test it when I have time.

**Comment by CHDman** [comment]
> https://github.com/rozhuk-im/msd_lite/tree/rejoin - branch to test rejoin feature.
> 
> `<rejoinTime>0</rejoinTime>` was added to config file. Also `rejoin_time=60` can be used as URL argument. 0 - off, non zero - interval in second to rejoin multicast group.
> 
> PS: I prefer to archive this project, it was free demo for https://github.com/rozhuk-im/msd, that now is open source and free.

Thanks a lot, I will test it when I have time.

**Comment by CHDman** [comment]
> https://github.com/rozhuk-im/msd_lite/tree/rejoin - branch to test rejoin feature.
> 
> `<rejoinTime>0</rejoinTime>` was added to config file. Also `rejoin_time=60` can be used as URL argument. 0 - off, non zero - interval in second to rejoin multicast group.
> 
> PS: I prefer to archive this project, it was free demo for https://github.com/rozhuk-im/msd, that now is open source and free.

It's worked, thanks~!
